# Generated by Django 3.0.1 on 2021-04-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improfile',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
