# Generated by Django 3.0.1 on 2021-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0002_auto_20210416_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_code', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
