# Generated by Django 3.0.1 on 2021-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0003_bookreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreq',
            name='is_status',
            field=models.IntegerField(default=0),
        ),
    ]
