# Generated by Django 3.0.1 on 2021-04-20 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Noteapp', '0004_bookreq_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreq',
            name='up',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
