# Generated by Django 3.0.1 on 2021-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0005_bookreq_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreq',
            name='uploadby',
            field=models.CharField(default='', max_length=120),
        ),
    ]
