# Generated by Django 3.0.1 on 2021-04-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0006_bookreq_uploadby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halldistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Hallname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noteapp.Halldistrict')),
            ],
        ),
    ]
