# Generated by Django 3.0.1 on 2021-04-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0007_halldistrict_hallname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50)),
                ('h_capacity', models.IntegerField()),
                ('h_location', models.CharField(max_length=2000)),
                ('h_images', models.ImageField(default='profile.png', upload_to='halls/')),
                ('h_number', models.CharField(max_length=12)),
                ('hallid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noteapp.Hallname')),
            ],
        ),
    ]
